//属性列表
var attributes=[
    {
      index:0,
      lable:"{name:jyy}",
      value:{name:"jyy"},
    },
    {
      index:1,
      lable:"{age:20}",
      value:{age:20},
    },
    {
      index:2,
      lable:"{isVue:true}",
      value:{isVue:true},
    }
  ]
// 单页面配置  
var single_pageview=[
    {
      index:0,
      lable:"布尔true",
      value:true
    },
    {
      index:1,
      lable:"布尔false",
      value:false
    },
    {
      index:2,
      lable:"字符串true",
      value:"true"
    },
    {
      index:3,
      lable:"字符串false",
      value:"false"
    },
    {
      index:4,
      lable:"数字1",
      value:1
    },
  ]

  // heatmap配置
  var heatmap_list=[
    {
      index:0,
      lable:"{}",
      value:{}
    },
    {
      index:1,
      lable:'string{}',
      value:"{}"
    },
    {
      index:2,
      lable:'""',
      value:""
    },
    {
      index:3,
      lable:"undefined",
      value:"undefined"
    },
    {
      index:4,
      lable:"null",
      value:null
    },
  ]

  // 点击图配置
  var clickmap_list=[
    {
      index:0,
      lable:"not_collect",
      value:"not_collect"
    },
    {
      index:1,
      lable:"default",
      value:"default"
    },
    {
      index:2,
      lable:'""',
      value:""
    },
    {
      index:3,
      lable:"undefined",
      value:"undefined"
    },
    {
      index:4,
      lable:"null",
      value:null
    },
    {
      index:5,
      lable:"false",
      value:false
    },
  ]
  export { attributes,single_pageview,heatmap_list,clickmap_list };